# Site settings
title: ShallmentMo's Blog
email: ShallmentMo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A coder
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shallmentmo.github.io" # the base hostname & protocol for your site
twitter_username: Shallment
github_username:  ShallmentMo

# Build settings
markdown: kramdown
